version: '3.9'
services:
    watched_system_api:
        container_name: watched_system_api
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn main:monitor_api --host 0.0.0.0 --port 8000 --reload
        volumes:
            - .:/app
        networks: 
            - monitored_net
        ports:
            - 8000:8000
        links:
            - monitor33y21_db
        depends_on:
            - monitor_migration

    monitor_migration:
        container_name: monitor_migration
        build:
            context: .
            dockerfile: Dockerfile
        image: monitor_api_image
        command: python database_initializer.py
        volumes:
            - .:/app
        networks: 
            - monitorplat_net        
        links:
            - monitor33y21_db
        depends_on:
            - monitor33y21_db

networks:
    monitored_net:
        driver: bridge