version: '3.9'
services:
    watched_system_api:
        container_name: watched_system_api
        build:
            context: .
            dockerfile: Dockerfile
        command: uvicorn main:app --host 0.0.0.0 --port 8000
        volumes:
            - .:/app
        networks: 
            - monitored_net
        ports:
            - 8000:8000
        links:
            - monitoring_agent

    monitoring_agent:
        container_name: monitoring_agent
        build:
            context: .
            dockerfile: Dockerfile_Monitor
        command: ["/bin/sh", "-c", "while true; do ./monitor_agent; sleep 300; done"]
        volumes:
            - .:/app
        networks: 
            - monitored_net

networks:
    monitored_net:
        driver: bridge